### ISSUE TITLE
cannot convert string to float

### ISSUE THREAD

**Issue by hunch-13** [M4d40/PMSFnestScript#34]
When I try to use the discord bot portion to rename a park with a ' in the name the following error occurs:

Ignoring exception in on_message
Traceback (most recent call last):
  File "/var/local/nestwatcher/ENV/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "tools.py", line 176, in on_message
    points = [float(p.strip()) for p in points]
  File "tools.py", line 176, in <listcomp>
    points = [float(p.strip()) for p in points]
ValueError: could not convert string to float: "Nor'west Optimist Park"

**Comment by ccev** [comment]
This is because you clicked the reaction for changing the nest marker's location, not the name. Make sure to click the 📝 emoji.
