### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by Zyahko** [M4d40/PMSFnestScript#55]
When running nests.py with a mix of discord channel ID and webhooks in the settings.json. The discord bot posts fine but then this message pops up when it attempts to send the webhooks.

```
/home/swks/.local/lib/python3.8/site-packages/discord/client.py:343: DeprecationWarning: logout is deprecated, use Client.close instead.
  await coro(*args, **kwargs)
/home/swks/.local/lib/python3.8/site-packages/discord/client.py:66: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  tasks = {t for t in task_retriever(loop=loop) if not t.done()}
Sending webhooks
Traceback (most recent call last):
  File "nests.py", line 253, in <module>
    bot.run(config.discord_token)
  File "/home/swks/.local/lib/python3.8/site-packages/discord/client.py", line 695, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 89, in add_signal_handler
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by pjorritsma** [comment]
With the latest version I didn't see this error. Do you still have this error Zyahko or is it resolve?
