### ISSUE TITLE
Creating emojis stuck

### ISSUE THREAD

**Issue by Pogodenhelder** [M4d40/PMSFnestScript#56]
Just updated to latest version after getting problems with emoji.
I ran the tools.py and deleted the old emoji server.

ran the nests.py.
All went well, when it wanted to make a new server it got stuck

Created emoji m111
Created emoji m315
Created emoji m273
Created emoji m161
Created emoji m451
Created emoji m79
Created emoji m459
Created emoji m325
Created emoji m7
Created emoji m396
Created emoji m185
Created emoji m283
Created emoji m328
Created emoji m535
Created emoji m100
Created emoji m194
Created emoji m265
Created emoji m339
Created emoji m10
Created emoji m165
Created emoji m370
Created emoji m258
Created emoji m77
Created emoji m191
Created emoji m114
Created emoji m255
Created emoji m252

and then nothing happens, the server is created went to it the bot is there.
but nothing gets posted later on.

in the end i stopped everything

Traceback (most recent call last):
  File "nests.py", line 211, in on_ready
    emote_refs = await get_emotes(bot, nesting_mons, config)
  File "/home/job-bais/nestwatcher/nestwatcher/discord.py", line 56, in get_emotes
    emoji = await free_guild.create_custom_emoji(name=emote_name, image=image)
  File "/home/job-bais/venv/lib/python3.6/site-packages/discord/guild.py", line 1664, in create_custom_emoji
    data = await self._state.http.create_custom_emoji(self.id, name, img, roles=roles, reason=reason)
  File "/home/job-bais/venv/lib/python3.6/site-packages/discord/http.py", line 178, in request
    await lock.acquire()
  File "/usr/lib/python3.6/asyncio/locks.py", line 181, in acquire
    yield from fut
concurrent.futures._base.CancelledError

**Comment by ccev** [comment]
How long did you wait before cancelling? Did it work on the second run?

**Comment by Pogodenhelder** [comment]
i waited for like 15 minutes or so, then aborted it.
I didnt test it after the cancellation, but i have a cron running and it did its job, so in the end it works.

**Comment by CarlosVMX1** [comment]
I'm having the same problem, let it running and when I get back to that screen, got this error lines

`Saved Geojson file
Sending webhooks
Created new emote server. Invite code: XXXXXXXXXX
Created emoji m1
Created emoji m258
Created emoji m4
...
Created emoji m161
Created emoji m418
Created emoji m165
Created emoji m167
Created emoji m431
Created emoji m185
Created emoji m187
Created emoji m191
Created emoji m193

Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "nests.py", line 251, in on_ready
    bot.emote_refs = await get_emotes(bot, nesting_mons, config)
  File "/path/nestwatcher/nestwatcher/discord.py", line 56, in get_emotes
    emoji = await free_guild.create_custom_emoji(name=emote_name, image=image)
  File "/usr/local/lib/python3.6/site-packages/discord/guild.py", line 1664, in create_custom_emoji
    data = await self._state.http.create_custom_emoji(self.id, name, img, roles=roles, reason=reason)
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 30008): Maximum number of emojis reached (50)

^CTraceback (most recent call last):
  File "nests.py", line 254, in <module>
    emote_refs = bot.emote_refs
AttributeError: 'Client' object has no attribute 'emote_refs'`

Looks it is locked when the first emote server gets full (50 emotes) and can't start saving at the second one, but at the first lines it is generating only one server, not sure if that can be the problem.
