### ISSUE TITLE
File "nests.py", line 181, in <module> with open(config.json_path, "w+") as file_:

### ISSUE THREAD

**Issue by MC0R3** [M4d40/PMSFnestScript#66]
After running nests.py, I'm geeting the following error:

```
Traceback (most recent call last):
  File "nests.py", line 181, in <module>
    with open(config.json_path, "w+") as file_:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Notifications are also not being posted to Discord through Poracle; maybe this is related?

**Comment by FimoJones** [comment]
You have not defined a `path` in the `Geojson` section of the config file and as a result, it errors.

**Comment by MC0R3** [comment]
Creating a path to the file did resolve this, thanks :)
